# Generated by Django 2.2 on 2020-07-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='nanme',
            new_name='name',
        ),
    ]
